# Generated by Django 5.0 on 2023-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
