# Generated by Django 5.0 on 2023-12-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_employeeaccount_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
