# Generated by Django 5.0 on 2023-12-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_employeeaccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaccount',
            name='phone',
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
