# Generated by Django 5.0 on 2023-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0002_profile_employee_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=6, null=True),
        ),
    ]
