# Generated by Django 5.0 on 2023-12-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='date',
            new_name='dateD',
        ),
    ]
