# Generated by Django 5.0 on 2023-12-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0006_rename_date_certification_dated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='platform',
            new_name='platforme',
        ),
    ]
