# Generated by Django 5.0 on 2023-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images_evenements/')),
                ('nom', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
            },
        ),
    ]
