# Generated by Django 5.0 on 2023-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_alter_evenement_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
